### PR TITLE
Change name of RPM to 'wp-cli0'

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Per conversation with @spheromak

### CODE REVIEW

**Comment by pantheon-circleci** [comment]
@greg-1-anderson, thanks for your PR! By analyzing the blame information on this pull request, we identified @joemiller to be a potential reviewer

**Comment by joemiller** [comment]
i didn't see the context behind this but sounds fine 👍

**Comment by spheromak** [comment]
@joemiller on systems the packag looks like `wp-cli-0.x-3.6.0.eoch.gitsha` 

other packages like drush are going `drush6-6.0.0` so this brings it in line with that.

**Comment by greg-1-anderson** [comment]
Context is just that the rpm name should avoid ending in "-[numeric]", because the rpm parser expects that to mean that the version part is starting. Turns out that the tools do not get confused, but it looks confusing for humans

**Pull request merged**
