### PR TITLE
Make rpm for wp-cli 1.0.0.

### PR DESCRIPTION
**Pull request by greg-1-anderson**

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
@joemiller / @spheromak: Fixed the 'os' thing. Also, changed the rules for automatically pushing to package cloud. PRs automatically push to internal-staging. When the PR is merged, the RPM is automatically pushed to internal. At this point, the cookbook will automatically update to it.

n.b. The rpm won't be the exact one pushed to internal-staging: it will be a rebuilt rpm that should be identical, save for its timestamp.

n.n.b. At this time, the cookbooks are only pulling in the wp-cli0 rpms, so this one (wp-cli1) won't go live until the cookbook is updated per https://github.com/pantheon-cookbooks/wp-cli/pull/7

If this all seems okay, then my plan is to merge the PR here to get an RPM automatically pushed to 'internal', and then use that to test the endpoint PR.  This is analogous to what I did manually a short time ago (manually build and pushed to internal).  The last time I did this (for wp-cli 0.24.1), I downloaded the rpm from internal-staging and pushed it to internal. Moving forward, though, it wouldn't be necessary at all to change the cookbook; just test with internal-staging, then merge the PR when ready to deploy.

Does that seem like a good workflow?

**Comment by joemiller** [comment]
@greg-1-anderson I am fine with the different RPM builds. We've talked about this before and it's less than ideal but I don't think we have a good or efficient solution, and at least the source of the two builds should be identical to mitigate that issue.

👍

**Comment by joemiller** [comment]
@greg-1-anderson it looks like this will also drop support for building the `wp-cli0` rpm's? If so, are we ok with that? for example, can we reasonably anticipate having to build a new wp-cli0 for a security patch? And, If wp-cli0 is dead, can we remove it from the existing nodes?

**Comment by greg-1-anderson** [comment]
@joemiller wp-cli0 is not going to get any further releases.  wp-cli1 is supposed to be compatible back to WordPress 3.7, so we probably don't need wp-cli0 any longer.  However, I'd like to remove it as a second step, after we're sure we don't need it.  Probably not too far in the future.

**Pull request merged**
